### ISSUE TITLE
Feedback for Fundamentals Lessons - REST APIs, Python, YAML

### ISSUE THREAD

**Issue by lmalhoit** [nre-learning/nrelabs-curriculum#100]
1.)	I can’t seem to scroll up in the terminal window.
2.)	You might want to tell people that they can type the commands in, but if they want to they can just run the snippet. Some people prefer to try it manually…it helps to drive home what you’re doing.
3.)	It’s possible people won’t know what libraries are. In stage 2, I know you’re just trying to familiarize folks with stuff, but telling “why you might be importing libraries and what they do for you might be helpful. Otherwise it might seem a little overwhelming. Also, terminology like “python data type” might be intimidating if they don’t know what that is or why we need it. I know there is a link to the Tech Library, and you can’t include EVERYTHING, but the less people have to go back and forth, and the more they know why they’re doing a specific thing, the better their experience will be.
4.)	Even words like JSON and XML may be meaningless and overwhelming if they are brand new
5.)	After running the “import json” command at the end it runs “print…blah blah blah” automatically. Then it prints out of course “There are 28 interfaces in this device.” It might be helpful to put a screen shot in the lesson and tell people what you’re doing, especially since it’s the first lesson. For example, talk about how you’re using the print command to print to the screen, and then how the % sign is actually a place holder, and the number of interfaces gets queried and that’s why “28” shows up in the end.
6.)	Finally, it’s a bit confusing that the “Go to the next stage in this lesson!” is just grayed out. Obviously it’s the end of the lesson, but I had to go check in the dropdown box. This is a bit nitpicky, but it would be better if you could just have a button that said “The End” or something. I thought the ultimate goal might be to gamify and have people submit what they’ve done, but I know there’s no signing in either…so that would be hard to do. Perhaps when you click “The End” or whatever, it shows a summary and maybe some more reference material? Doesn’t have to be a Juniper Call To Action or anything.

**Comment by Mierdin** [comment]
Thanks for this early feedback @lmalhoit! Looking at the improvements that have been made to the site since this, as well as the content, I'm comfortable calling this fixed. So I'll close this issue. Thanks again!
