### ISSUE TITLE
Style checks and enforcement in CI

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/nrelabs-curriculum#201]
A nontrivial amount of the time spent in curriculum review is spent doing basic grammar, spelling, and formatting edits. This is not sustainable, and we should look to automate the application of our curriculum standards to incoming lesson contributions so everyone's contribution experience is much smoother.

Not just spellchecking, but also making sure the headers for all lab guides are correct, headers of all levels have appropriate capitalization, etc. Should build a script to check all these things, and run in CI

Could also check for snippet order as well (though in the long-term the snippet index shouldn't be a thing at all)

It should also be easily extensible so that if someone wants to add a word to a dictionary, they can do that easily.

Don't forget to update docs on how this is being done.

**Comment by smk4664** [comment]
For spellchecking, the easiest one to create a dictionary for is yaspeller https://github.com/ai/yaspeller-ci.  The dictionary can be stored in the yaspeller config file or as a separate file. 

For linting, Markdownlint seems like a good fit, and has a cli option that works in ci/cd  https://github.com/igorshubovych/markdownlint-cli.  This can also take a configuration file.   This attempts to set a standard "Style Guide".  But we may need to extend or rewrite to support rules such as capitalization in headings.

For grammer, the only option I found for CI is write-good https://github.com/btford/write-good.  There is a set of grammar rules that this will check for. 

I believe that we can enable spell-checking and have it fail in Travis-ci as this will catch spelling errors, and adding to the dictionary is easy. For the linter and grammar, we may be able to set this to check only changed files, and have it only report, not fail the pipeline.

**Comment by smk4664** [comment]
The spellchecker is done, I will put in a pull request tomorrow.  I am working on updating the docs now.

**Comment by smk4664** [comment]
I definitely commented too early.  I found some issues with yaspeller-ci, I am looking into other options.
