### ISSUE TITLE
Broken Lesson 21 (Troubleshooting IP phone)

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/nrelabs-curriculum#263]
The troubleshooting lesson needs some work

- The `cd /antidote` command isn't issued until the second snippet, so the first snippet that calls `phone.sh` doesn't work.
- I also had trouble with the SIP client even when running in the correct directory. Would run but exit after 2 seconds or so

**Comment by cloudtoad** [comment]
Ack... will work on this this weekend.

**Comment by Mierdin** [comment]
I also had trouble with the SIP client even when running in the correct directory. Would run but exit after 2 seconds or so

**Comment by Mierdin** [comment]
For some reason, I continually forget that this lesson requires NET_ADMIN privileges. Adding these images to the deployment for Syringe makes the "brokenness" go away. For everything else, I opened #299.
