### ISSUE TITLE
Allow multiple Antidote clusters

### ISSUE THREAD

**Issue by jameskellynet** [nre-learning/nrelabs-curriculum#3]
Today we have FQDNs in the codebase, so the project is always deployed assuming the same DNS config and reachable at the same place. This need to be parameterized for a few reasons:

 - We need to be able to stage and test new commits and stress the system outside of prod in a test/stage environment
 - Contributors need to be able to test their lessons
 - We'd like to blue-green deploy clusters to roll back in case of catastrophic outages

**Comment by Mierdin** [comment]
This has been in place for some time, closing
