### ISSUE TITLE
Error reading SSH protocol banner in Ansible lesson

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/nrelabs-curriculum#304]
Occasionally, various steps in the Ansible lesson fail with `Error reading SSH protocol banner`. Unfortunately this has been pretty difficult to reproduce - it only happens part of the time.

```
[antidote@ansible stage2]$ ansible-playbook facts.yml

PLAY [Ansible Facts] ********************************************************************************

TASK [Gathering Facts] ******************************************************************************
fatal: [vqfx1]: FAILED! => changed=false 
  ansible_facts: {}
  failed_modules:
    junos_facts:
      ansible_facts:
        discovered_interpreter_python: /usr/bin/python3.6
      failed: true
      invocation:
        module_args:
          config_format: text
          gather_network_resources: null
          gather_subset:
          - all
          host: null
          password: null
          port: null
          provider: null
          ssh_keyfile: null
          timeout: null
          transport: null
          username: null
      msg: 'Negotiation failed: Error reading SSH protocol banner'
  msg: |-
    The following modules failed to execute: junos_facts
```

https://stackoverflow.com/questions/25609153/paramiko-error-reading-ssh-protocol-banner seems to indicate this could be a problem with congestion on the server.

May want to consider playing around with options in the vqfx image to address this, but the first step is figuring out how to reliably reproduce the behavior.

**Comment by t0i** [comment]
I can confirm I ran into this issue and had to run the playbook 3 times, the 3rd time it worked. First two times it spit out identical error to what @Mierdin posted.

**Comment by Mierdin** [comment]
@t0i Interesting that re-running it in the same lesson instance sometimes results in a better result. Thanks for the update. We'll continue to dig into this and get a fix in for the next release in a week or two

**Comment by IPvSean** [comment]
is this issue still popping up?

**Comment by Mierdin** [comment]
I believe so. As discussed on the phone, I'll try to tweak the timeout values for paramiko and see if that resolves the issue.

**Comment by Mierdin** [comment]
The fix should be in https://github.com/ansible/ansible/pull/68184 - the trick now is to wait for that to be merged and make it into a release, then we can upgrade to that version.
