### ISSUE TITLE
Need to set a valid email address in GIT before being allowed to commit

### ISSUE THREAD

**Issue by consta-jnpr** [nre-learning/nrelabs-curriculum#89]
I couldn't copy the text over from the webpage, but here's a screenshot.
![screen shot 2018-10-11 at 4 38 40 pm](https://user-images.githubusercontent.com/33482291/46812046-34c49900-cd74-11e8-92c3-fbef5e698551.png)

You could add this as a step after the *git init* one, where the user sets a name and email (global or local).

**Comment by consta-jnpr** [comment]
Can we add this step by modifying the `lessons/lesson-17/stage1/guide.md` file?
I can send a pull request if we agree on the email address (which will be static and the same for everyone)

**Comment by Mierdin** [comment]
@consta-jnpr Hey, thanks! Yes, that's a good idea, and feel free to amend the lesson guide in a PR. Just pick an obviously fake email address and name.

Btw the copy+paste functionality isn't currently supported, but we are working to make this happen. Opened in https://github.com/nre-learning/antidote/issues/31

**Comment by Mierdin** [comment]
This was fixed a while back; closing.
